[project]
name = "exoplanetdsa230"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "numpy>=2.1.2",
    "pandas>=2.2.3",
    "pathlib>=1.0.1",
    "polars>=1.12.0",
]
